### ISSUE TITLE
Could not connect to zcashd. Disconnected 0.9.2. 

### ISSUE THREAD

**Issue by Fi3ei1** [adityapk00/zecwallet-lite#37] opened 2020-02-29 11:18 UTC
OS Windows7 The wallet worked as normal. Connection through AdvOR. Version Zecwallet.FullNode.0.9.2. 
![Screenshot_1](https://user-images.githubusercontent.com/61346691/75606479-8e567080-5aed-11ea-8e1b-fcbcceb430f5.png)
![Screenshot_2](https://user-images.githubusercontent.com/61346691/75606481-90203400-5aed-11ea-9033-a4172df50571.png)

Rebooted and reinstalled the wallet. Did not help

What is the problem do not understand?

**Comment by adityapk00** [comment] 2020-02-29 15:49
This is likely duplicate of this bug: https://github.com/ZcashFoundation/zecwallet/issues/240

You are likely running into the underlyinf zcashd bug here: zcash/zcash#4301

You need to do a reindex.

If you are using Windows:

1. Download the ZIP archive
2.Unzip Zecwallet.FullNode-0.9.2-win.zip
3.Open a Command Prompt
4.cd into resources/bin/win in the extracted archive
5.Run zcashd.exe

    This should show you an error, so you can confirm what error you are actually running into.

To reindex, do:
6. zcashd.exe -reindex

(Note that a reindex can take several hours/days

**Comment by adityapk00** [comment] 2020-02-29 15:50
Closing this, because this seems like a full node issue (Not the lightclient).

**Closed by adityapk00** 2020-02-29 15:50 UTC

**Comment by veikkoeeva** [comment] 2020-03-09 14:30
I add here in case someone reads that while running Zecwallet Fullnode v0.9.5 reindex helps, the issues comes back after one closes the command prompt and starts the application. The issue resurfaces also when starting from the command prompt. So it appears running reindex helps but one shouldn't close the command line or else the problems returns.
