### ISSUE TITLE
 Error Initializing Lightclient Error: failed to fill whole buffer

### ISSUE THREAD

**Issue by protongirl** [adityapk00/zecwallet-lite#54] opened 2020-05-09 14:35 UTC
I have money in this Wallet but cant acces :( only way that I found is %Appdata% C:\blabla\AppData\Roaming\Zcash and delete zecwallet-light-wallet then I can create new wallet, but I dident save the seed :/ can anyone help me please???

I have Zecwallet Lite v1.1.9

![Screenshot_1](https://user-images.githubusercontent.com/65078024/81476609-1904cb80-9213-11ea-84d8-387895567650.png)

**Comment by adityapk00** [comment] 2020-05-09 15:33
Duplicate of #51

**Closed by adityapk00** 2020-05-09 15:33 UTC
