### ISSUE TITLE
Improvement: Please add SOCKS 5 proxy support

### ISSUE THREAD

**Issue by gousasin** [adityapk00/zecwallet-lite#19] opened 2019-11-11 15:12 UTC
Hello

I would like to suggest adding support for using a SOCKS 5 proxy. An option to enter a SOCKS 5 proxy IP and port in the settings/connections tab would be useful for some users.

Thanks

**Comment by rex4539** [comment] 2020-03-07 09:18
This is actually a prerequisite for Tor support.

**Comment by adityapk00** [comment] 2020-04-06 02:52
Duplicate of #26

**Closed by adityapk00** 2020-04-06 02:52 UTC

**Comment by BenDover6969** [comment] 2020-11-27 00:41
Why was this closed? Is there a way to use Zecwallet Lite with Tor?
