### ISSUE TITLE
Unhandled error message

### ISSUE THREAD

**Issue by rex4539** [adityapk00/zecwallet-lite#14] opened 2019-10-31 18:40 UTC
Reproducibility: always

Steps:
1. On an account with low funds, send a transaction.
2. Send another transaction (error message appears).
3. Quit the app.
4. Launch the app.
5. Send another transaction.

What happened:

<img width="532" alt="Screenshot 2019-10-31 at 20 34 45" src="https://user-images.githubusercontent.com/227442/67976148-37638c00-fc1e-11e9-8eaf-8b073daeeada.png">

Expected result:

<img width="532" alt="Screenshot 2019-10-31 at 20 38 00" src="https://user-images.githubusercontent.com/227442/67976353-9a552300-fc1e-11e9-8876-a734421827fa.png">

**Comment by adityapk00** [comment] 2019-10-31 22:02
The problem here is the same as the mempool issue. When we restart, we don't know that the wallet has an outgoing transaction pending in the mempool, and the lightwallet protocol doesn't tell us this, so we assume we can send a Tx. The wallet constructs the Tx and even broadcasts it, but the Tx is then rejected during broadcast because the full node rejects it (Because this Tx spends notes that are already spent (but not mined) in another Tx that is in the mempool)

**Comment by adityapk00** [comment] 2020-04-06 02:51
Duplicate of #8

**Closed by adityapk00** 2020-04-06 02:51 UTC
